### ISSUE TITLE
Removing Cargo.lock broke the build

### ISSUE THREAD

**Issue by jasonwyatt** [braidery/braid-lib#6]
```
jason@sunspear ~/GitHub/braid-lib (develop)$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/sfackler/rust-postgres`
error: no matching package for override `https://github.com/rust-lang/crates.io-index#postgres:0.13.6` found
location searched: https://github.com/sfackler/rust-postgres
version required: = 0.13.6
```

This happens for me on develop, but not on master, and the only difference of note is the lack of the lock file.

**Comment by jasonwyatt** [comment]
This also seems to be what caused #5 to fail

**Comment by ysimonson** [comment]
Ah, I see what happened. I renamed the repo at the same time as opening the PR to remove `Cargo.lock`. Because of this, TravisCI didn't pick up the PR and run tests. I saw the green checkmark and assumed tests ran.

Will do some further digging tomorrow. I'm hoping it's still possible to get rid of `Cargo.lock`, but it seems to be conflicting with the override for `rust-postgres`.

**Comment by ysimonson** [comment]
Going to go ahead and revert, because the dependencies are in too much flux at the moment. See comment here: https://github.com/braidery/braid-lib/pull/7
